pipeline {
  agent any
  stages {

    stage("Cleanup Workspace") {
      steps {
        deleteDir()
      }
    }
    stage("Checkout MobileAutomata") {
      steps {
        git branch: 'master',
        url: 'https://github.com/prateeksethiDev/MobileAutomata.git',
        credentialsId: 'GitDevAccount'
      }
    }
    stage("Build and run tests") {
      steps {
        echo 'Running Test Automation'
    sh label: '', script: 'mvn -f MobileAutomata/pom.xml clean test'
      }
    }
    stage("Email the report") {
      steps {
        emailext attachLog: true, body: '''Hello Admin,

Please find the the attached test execution report for project: $PROJECT_NAME - BUILD# - $BUILD_NUMBER

Build url is : $BUILD_URL

''', compressLog: true, subject: '[$BUILD_STATUS] - $PROJECT_NAME - BUILD# - $BUILD_NUMBER', to: 'prateeksethiDev@gmail.com'
      }
    }
    
  }
}
